// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	auth "github.com/Weit145/proto-repo/auth"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GRPCConfirmUser is an autogenerated mock type for the GRPCConfirmUser type
type GRPCConfirmUser struct {
	mock.Mock
}

// RegistrationUser provides a mock function with given fields: ctx, token
func (_m *GRPCConfirmUser) RegistrationUser(ctx context.Context, token string) (*auth.CookieResponse, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RegistrationUser")
	}

	var r0 *auth.CookieResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.CookieResponse, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.CookieResponse); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.CookieResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGRPCConfirmUser creates a new instance of GRPCConfirmUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGRPCConfirmUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *GRPCConfirmUser {
	mock := &GRPCConfirmUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
