// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/Weit145/proto-repo/auth"

	mock "github.com/stretchr/testify/mock"
)

// GRPCLoginUser is an autogenerated mock type for the GRPCLoginUser type
type GRPCLoginUser struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: ctx, _a1, password
func (_m *GRPCLoginUser) Authenticate(ctx context.Context, _a1 string, password string) (*auth.CookieResponse, error) {
	ret := _m.Called(ctx, _a1, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *auth.CookieResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*auth.CookieResponse, error)); ok {
		return rf(ctx, _a1, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *auth.CookieResponse); ok {
		r0 = rf(ctx, _a1, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.CookieResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, _a1, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGRPCLoginUser creates a new instance of GRPCLoginUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGRPCLoginUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *GRPCLoginUser {
	mock := &GRPCLoginUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
