// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/Weit145/proto-repo/auth"

	mock "github.com/stretchr/testify/mock"
)

// GRPCRegistrationUser is an autogenerated mock type for the GRPCRegistrationUser type
type GRPCRegistrationUser struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, login, email, password, username
func (_m *GRPCRegistrationUser) CreateUser(ctx context.Context, login string, email string, password string, username string) (*auth.Okey, error) {
	ret := _m.Called(ctx, login, email, password, username)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *auth.Okey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*auth.Okey, error)); ok {
		return rf(ctx, login, email, password, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *auth.Okey); ok {
		r0 = rf(ctx, login, email, password, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Okey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, login, email, password, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGRPCRegistrationUser creates a new instance of GRPCRegistrationUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGRPCRegistrationUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *GRPCRegistrationUser {
	mock := &GRPCRegistrationUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
