// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/Weit145/proto-repo/auth"

	mock "github.com/stretchr/testify/mock"
)

// GRPCRefreshToken is an autogenerated mock type for the GRPCRefreshToken type
type GRPCRefreshToken struct {
	mock.Mock
}

// RefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *GRPCRefreshToken) RefreshToken(ctx context.Context, refreshToken string) (*auth.AccessTokenResponse, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *auth.AccessTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.AccessTokenResponse, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.AccessTokenResponse); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AccessTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGRPCRefreshToken creates a new instance of GRPCRefreshToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGRPCRefreshToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *GRPCRefreshToken {
	mock := &GRPCRefreshToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
