// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GRPCLogOutUser is an autogenerated mock type for the GRPCLogOutUser type
type GRPCLogOutUser struct {
	mock.Mock
}

// LogOutUser provides a mock function with given fields: ctx, token
func (_m *GRPCLogOutUser) LogOutUser(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for LogOutUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGRPCLogOutUser creates a new instance of GRPCLogOutUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGRPCLogOutUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *GRPCLogOutUser {
	mock := &GRPCLogOutUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
